window.SHADOWING = {
  generatedAt: "2026-08-06T18:26:33Z",
  decks: [
    {
      id: "daily-life",
      name: "Daily Life",
      lines: [
        "I must've <b>hit the snooze button</b> like four times this morning.",
        "If you <b>hit the snooze button</b> again, we're gonna miss the bus.",
        "I keep my phone across the room so I can't just <b>hit the snooze button</b> and pass back out.",
        "You wanna <b>grab a coffee</b> before the meeting?",
        "I'm just gonna <b>grab a coffee</b> and head straight in.",
        "We should <b>grab a coffee</b> sometime and catch up.",
        "Give me ten minutes to <b>get ready</b> and we can go.",
        "The kids are still <b>getting ready</b> for school.",
        "I need to <b>get ready</b> \u2014 I'm meeting them at seven.",
        "Sorry, I'm <b>running late</b> \u2014 traffic is insane.",
        "Can you text her and say we're <b>running late</b>?",
        "He's always <b>running late</b> for everything.",
        "<b>On my way</b>, be there in five!",
        "I'm <b>on my way</b> to the office right now.",
        "Just tell them I'm <b>on my way</b>.",
        "Let me just <b>hop in the shower</b> real quick.",
        "I'll <b>hop in the shower</b> and then we can head out.",
        "Give me a sec, I'm about to <b>hop in the shower</b>.",
        "It's Saturday, I'm gonna <b>sleep in</b>.",
        "I finally got to <b>sleep in</b> this morning.",
        "No alarm tomorrow \u2014 I'm <b>sleeping in</b>.",
        "I'm so sorry I'm late, I <b>slept through my alarm</b>.",
        "She <b>slept through her alarm</b> and missed her flight.",
        "Please don't <b>sleep through your alarm</b> again tomorrow.",
        "I didn't <b>roll out of bed</b> until almost noon.",
        "He just <b>rolled out of bed</b> \u2014 look at his hair.",
        "Some mornings it's so hard to <b>roll out of bed</b>.",
        "Let me <b>throw on</b> a shirt and I'll be right down.",
        "I just <b>threw on</b> whatever was clean.",
        "Give me a minute to <b>throw on</b> some clothes.",
        "Don't talk to me before coffee \u2014 I'm <b>not a morning person</b>.",
        "She's really <b>not a morning person</b>, so mornings are rough around here.",
        "Sorry if I'm grumpy, I'm just <b>not a morning person</b>.",
        "I'll email you <b>first thing in the morning</b>.",
        "Let's deal with it <b>first thing in the morning</b>.",
        "She goes for a run <b>first thing in the morning</b>, every single day.",
        "Can you <b>do the dishes</b> while I put the kids to bed?",
        "I cooked, so it's only fair that you <b>do the dishes</b>.",
        "There's a huge pile in the sink - I really need to <b>do the dishes</b>.",
        "Don't forget to <b>take out the trash</b> - tomorrow's pickup day.",
        "I already <b>took out the trash</b>, so we're good.",
        "Hey, can you <b>take out the trash</b> on your way out?",
        "Let me <b>throw in a load of laundry</b> before we leave.",
        "I'll <b>throw in a load of laundry</b> real quick and then we can watch the movie.",
        "My morning routine: coffee, check email, <b>throw in a load of laundry</b>.",
        "<b>Make your bed</b> before you leave for school.",
        "I never <b>make the bed</b> on weekdays - no time.",
        "The room looks so much better once you <b>make the bed</b>.",
        "I'm too tired to <b>make dinner</b> - let's just order in.",
        "You set the table and I'll <b>make dinner</b>.",
        "Mom's gonna <b>make dinner</b> around seven, so don't fill up on snacks.",
        "I keep meaning to clean the garage, but I never <b>get around to</b> it.",
        "I finally <b>got around to</b> fixing that leaky faucet.",
        "Once things calm down, I'll <b>get around to</b> sorting out the closet.",
        "Just <b>load the dishwasher</b> and I'll run it before bed.",
        "Can you <b>load the dishwasher</b> while I wipe the table?",
        "He never rinses anything before he <b>loads the dishwasher</b>.",
        "Let me just <b>wipe down the counters</b> and then the kitchen's done.",
        "Can you <b>wipe down the counter</b> after you make your sandwich?",
        "I always <b>wipe down the counters</b> before I start cooking.",
        "Can you <b>pick up around the house</b> a little before the guests get here?",
        "I spent all morning <b>picking up around the house</b>.",
        "The place is a mess - let's just <b>pick up around the house</b> real quick.",
        "The dishes are dry - can you <b>put them away</b>?",
        "I'll <b>put the dishes away</b> while you finish cooking.",
        "Don't just leave them on the rack, <b>put the dishes away</b>.",
        "You're an adult - <b>clean up after yourself</b>.",
        "I'm not your maid; please <b>clean up after yourself</b>.",
        "The kids are finally old enough to <b>clean up after themselves</b>.",
        "I'm gonna <b>run to the store</b> - need anything?",
        "We're out of milk; I'll <b>run to the store</b> real quick.",
        "Can you <b>run to the store</b> and grab some eggs?",
        "I've gotta <b>run some errands</b> this afternoon, so text me if you need anything.",
        "She was out all morning <b>running errands</b> and didn't get home till two.",
        "Can we push the call back an hour? I need to <b>run a few errands</b> first.",
        "Can you <b>pick up</b> the kids from practice at five?",
        "I'll <b>pick up</b> some Thai food on my way home.",
        "Did you <b>pick up</b> my prescription while you were out?",
        "I need to <b>drop off</b> a package at the post office.",
        "Can you <b>drop</b> the kids <b>off</b> at school on your way in?",
        "She <b>dropped</b> me <b>off</b> out front and went to park.",
        "I'll <b>swing by</b> the pharmacy and grab your meds.",
        "Wanna <b>swing by</b> my place before the movie?",
        "Can you <b>swing by</b> the office and grab my laptop?",
        "I'll grab some wine <b>on my way home</b>.",
        "Send me a list and I'll stop at the store <b>on my way home</b>.",
        "I tried calling you <b>on my way home</b> but it went to voicemail.",
        "We should <b>stock up on</b> water before the storm hits.",
        "I always <b>stock up on</b> coffee when it's on sale.",
        "They <b>stocked up on</b> snacks for the road trip.",
        "I just need to <b>grab a few things</b>, give me five minutes.",
        "Can you <b>grab a couple things</b> while you're at Target?",
        "Let me <b>grab a few things</b> for dinner and we'll head back.",
        "It's getting late, I should <b>head out</b>.",
        "We're gonna <b>head out</b> around noon to beat the traffic.",
        "You ready to <b>head out</b>?",
        "Do you need anything <b>while I'm out</b>?",
        "I'll drop the letters off <b>while I'm out</b>.",
        "Can you keep an eye on the dog <b>while I'm out</b>?",
        "<b>We're out of</b> milk again.",
        "Add it to the list, <b>we're out of</b> paper towels.",
        "I think <b>we're out of</b> coffee; can you grab some?",
        "You wanna <b>grab a bite</b> after work?",
        "We <b>grabbed a bite</b> at that new taco place downtown.",
        "I'm starving, let's <b>grab a bite</b> somewhere real quick.",
        "It's almost seven and I'm beat, so let's <b>call it a day</b>.",
        "We got through most of the list, so I think we can <b>call it a day</b>.",
        "My back is killing me \u2014 I'm gonna <b>call it a day</b> and finish this tomorrow.",
        "You've been sick all week \u2014 just <b>take it easy</b> this weekend.",
        "Alright man, good seeing you. <b>Take it easy</b>.",
        "The doctor told me to <b>take it easy</b> for a few days after the surgery.",
        "We <b>ran out of time</b> in the meeting, so we'll pick it up tomorrow.",
        "I wanted to hit the gym but I <b>ran out of time</b> this morning.",
        "Hurry up, we're <b>running out of time</b>!",
        "Sorry I'm late, I was reading and totally <b>lost track of time</b>.",
        "We were talking for hours \u2014 I completely <b>lost track of time</b>.",
        "It's so easy to <b>lose track of time</b> when you're gaming.",
        "My flight's delayed three hours, so I'm just <b>killing time</b> at the gate.",
        "We got there early and had to <b>kill time</b> in a coffee shop.",
        "I play games on my phone to <b>kill time</b> on the bus.",
        "Can we talk later? I'm totally <b>swamped</b> right now.",
        "I've been <b>swamped</b> at work all week.",
        "Sorry for the slow reply, I was <b>swamped</b> with emails.",
        "I barely slept all week, so I'm gonna <b>catch up on sleep</b> this weekend.",
        "After the newborn phase, we spent months trying to <b>catch up on sleep</b>.",
        "I finally <b>caught up on sleep</b> over the holidays.",
        "I like to <b>wind down</b> with a book before bed.",
        "Give me a sec to <b>wind down</b> \u2014 that was a stressful call.",
        "A glass of wine helps me <b>wind down</b> after work.",
        "Anyway, it's getting late \u2014 <b>I should get going</b>.",
        "<b>I should get going</b>, I've got an early start tomorrow.",
        "This was fun, but <b>I should probably get going</b>.",
        "I'm totally <b>wiped out</b> after that double shift.",
        "That long drive left me completely <b>wiped out</b>.",
        "The kids are <b>wiped out</b> from the pool \u2014 they'll be asleep in minutes."
      ]
    },
    {
      id: "small-talk",
      name: "Small Talk",
      lines: [
        "Hey man, <b>how's it going</b>? Haven't seen you around the office lately.",
        "<b>How's it going</b> today? You finding everything okay?",
        "Oh hey, <b>how's it going</b>? I love that jacket, by the way.",
        "Yo, <b>what's up</b>? You coming to the thing tonight?",
        "Hey, <b>what's up</b>, man! It's been forever.",
        "<b>What's up</b>? I saw you texted me earlier.",
        "Wow, it's been forever - <b>how've you been</b>?",
        "Good to see you! So <b>how've you been</b>? Still at the same job?",
        "Hey Sarah, <b>how've you been</b>? The kids must be huge now.",
        "Marcus! <b>Long time no see</b> - what have you been up to?",
        "Well, <b>long time no see</b>! I was just thinking about you the other day.",
        "<b>Long time no see</b>, stranger. You look great.",
        "Hey, so <b>good to see you</b>! It's been way too long.",
        "<b>Good to see you</b>, man. Thanks for coming out tonight.",
        "Oh wow, <b>good to see you</b> - how's the family?",
        "So <b>what have you been up to</b> these days? Anything exciting?",
        "<b>What have you been up to</b> lately? Still doing the photography thing?",
        "Tell me everything - <b>what have you been up to</b>?",
        "Hey! <b>It's been a while</b>, huh? How are things?",
        "Wow, <b>it's been a while</b> since we last talked.",
        "<b>It's been a while</b>! I feel like I haven't seen you since the wedding.",
        "Hey, <b>what's new</b> with you? Anything going on?",
        "So <b>what's new</b>? Fill me in.",
        "<b>What's new</b>, man? How's the new apartment?",
        "Hi, I'm David - <b>nice to meet you</b>.",
        "<b>Nice to meet you</b>! I've heard so much about you.",
        "So <b>nice to finally meet you</b> in person after all those emails.",
        "Hey, <b>how's your day going</b>? Busy one?",
        "<b>How's your day going</b> so far? Mine's been crazy.",
        "Hi there - <b>how's your day going</b>?",
        "Hey there, <b>how are you doing</b>?",
        "<b>How are you doing</b>? You holding up okay after last week?",
        "So <b>how are you doing</b> these days? Everything good?",
        "<b>Hey there</b>! I didn't expect to run into you here.",
        "<b>Hey there</b>, stranger! Where've you been hiding?",
        "Oh, <b>hey there</b> - good timing, I was just about to call you.",
        "Wow, it's really <b>nice out</b> today - want to grab lunch outside?",
        "Finally some sun. It's so <b>nice out</b> I might just walk home.",
        "It's <b>nice out</b>, huh? Perfect weather for the game later.",
        "<b>Crazy weather</b> we're having, right? Sunny this morning, pouring now.",
        "Can you believe this <b>crazy weather</b>? It was snowing yesterday.",
        "What is up with this <b>crazy weather</b>? I don't even know how to dress anymore.",
        "It's <b>supposed to</b> rain all weekend, so much for the hike.",
        "I heard it's <b>supposed to</b> be nice on Saturday - finally.",
        "It was <b>supposed to</b> snow last night, but nothing happened.",
        "Morning! <b>How was your weekend</b>?",
        "Hey, <b>how was your weekend</b>? Do anything fun?",
        "<b>How was your weekend</b>? Mine flew by, as usual.",
        "It's Friday! <b>Any plans for the weekend</b>?",
        "<b>Any plans for the weekend</b>, or just taking it easy?",
        "So, <b>any plans for the weekend</b>? The weather's supposed to be great.",
        "Hey, good to see you! <b>Staying busy</b>?",
        "Work's been nuts, so, you know, <b>staying busy</b>.",
        "How've you been? - Oh, <b>staying busy</b>, the usual.",
        "What'd you do this weekend? - <b>Not much</b>, honestly. Just chilled.",
        "What's new with you? - Eh, <b>not much</b>. Same old.",
        "You up to anything tonight? - <b>Not much</b>, might just stay in.",
        "Honestly I just <b>took it easy</b> this weekend - slept in, watched a ton of TV.",
        "We <b>took it easy</b> on Sunday after the party Saturday night.",
        "I was wiped out, so I just <b>took it easy</b> at home.",
        "Better grab some water - it's <b>gonna be a hot one</b> today.",
        "Weather guy says it's <b>gonna be a hot one</b> this weekend.",
        "Ugh, another scorcher. <b>Gonna be a hot one</b> again.",
        "Alright, <b>I'll let you go</b> \u2014 I know you've got a busy day.",
        "Well, <b>I'll let you go</b>, but it was great catching up.",
        "I should run, so <b>I'll let you go</b>. Talk soon!",
        "<b>Good seeing you</b>, man \u2014 we should grab a beer sometime.",
        "It was <b>good seeing you</b> again! Tell Sarah I said hi.",
        "<b>Good seeing you</b>! Don't be a stranger.",
        "Well, <b>nice meeting you</b>, Dave. Hope to see you around.",
        "It was really <b>nice meeting you</b> \u2014 good luck with the move!",
        "<b>Nice meeting you</b>! Let's connect on LinkedIn.",
        "Okay, I'll see you next week. <b>Take care</b>!",
        "<b>Take care</b>, and say hi to the family for me.",
        "Thanks again for everything. <b>Take care</b> of yourself.",
        "We've got so much to talk about \u2014 <b>let's catch up soon</b>.",
        "<b>Let's catch up soon</b>, okay? It's been way too long.",
        "I really have to run, but <b>let's catch up soon</b> \u2014 coffee next week?",
        "This was fun \u2014 <b>we should hang out sometime</b>.",
        "Hey, <b>we should hang out</b> more, seriously.",
        "<b>We should hang out sometime</b> when things calm down.",
        "Cool, sounds good. <b>Talk soon</b>!",
        "Gotta run \u2014 <b>talk soon</b>, yeah?",
        "Thanks for the call. <b>Talk soon</b>.",
        "It was great working with you \u2014 <b>keep in touch</b>!",
        "Don't be a stranger, okay? <b>Keep in touch</b>.",
        "<b>Keep in touch</b> \u2014 you've got my number."
      ]
    },
    {
      id: "native-fillers-conversation-glue",
      name: "Native Fillers & Conversation Glue",
      lines: [
        "It was one of those days, <b>you know</b>, where nothing goes right.",
        "I didn't want to make it a big thing, <b>you know</b>?",
        "He's just, <b>you know</b>, a little intense sometimes.",
        "I'll be there around eight. <b>I mean</b>, maybe eight thirty, depending on traffic.",
        "<b>I mean</b>, it's not the worst idea, but I'd do it differently.",
        "He's not rude exactly. <b>I mean</b>, he just doesn't say much.",
        "It was, <b>like</b>, the best concert I've ever been to.",
        "We waited for, <b>like</b>, two hours.",
        "And she was <b>like</b>, 'No way,' and I just laughed.",
        "I'm <b>kind of</b> tired, honestly. Can we do it tomorrow?",
        "It's <b>kind of</b> a long story.",
        "I <b>kind of</b> regret saying that.",
        "'Did you finish?' '<b>Sort of</b>. I've got the main part done.'",
        "It's <b>sort of</b> blue, sort of gray - hard to describe.",
        "I <b>sort of</b> knew it was coming.",
        "'Are you coming?' '<b>Well</b>, it depends on when we finish.'",
        "<b>Well</b>, I wouldn't put it quite like that.",
        "<b>Well</b>, that's one way to look at it.",
        "<b>Um</b>, I think it was Tuesday? Let me check.",
        "The answer is, <b>uh</b>, forty-two, I believe.",
        "<b>Um</b>, actually, can I say something?",
        "<b>Let me think</b>... I want to say it was around 2019?",
        "Best restaurant downtown? <b>Let me think</b> for a sec.",
        "<b>Let me think</b> about it and I'll get back to you.",
        "He's, <b>how do I put this</b>, not the most reliable guy.",
        "The results were - <b>how do I put this</b> - disappointing.",
        "<b>How do I put this</b> without sounding harsh? It just wasn't good.",
        "We can grab coffee <b>or something</b> later.",
        "He said he was sick <b>or something</b>, I don't remember exactly.",
        "Just leave it on the desk <b>or something</b>.",
        "<b>I don't know</b>, it just feels like the wrong move to me.",
        "It was fine, I guess. <b>I don't know</b>.",
        "<b>I don't know</b>, maybe we're overthinking this.",
        "Pass me the - <b>what do you call it</b> - the spatula.",
        "It's that, <b>what do you call it</b>, the thing that holds the door open.",
        "She works in, <b>what do you call it</b>, logistics? Supply chain, anyway.",
        "<b>Let's see</b>... if we leave now, we'll get there by six.",
        "What do I have on Friday? <b>Let's see</b>.",
        "<b>Let's see</b>, that's three coffees and a muffin, right?",
        "<b>To be honest</b>, I didn't really love the movie \u2014 I almost fell asleep.",
        "I haven't thought about it that much, <b>to be honest</b>.",
        "<b>To be honest</b> with you, I think you can do a lot better than that job.",
        "He was late, but <b>to be fair</b>, the traffic was insane this morning.",
        "<b>To be fair</b>, she did warn us it would be hard.",
        "The place is pricey, but <b>to be fair</b>, the portions are huge.",
        "<b>If you ask me</b>, they're charging way too much for that apartment.",
        "That whole plan is a mess, <b>if you ask me</b>.",
        "<b>If you ask me</b>, he should just apologize and move on.",
        "I'd love to come, but <b>the thing is</b>, I've got work early tomorrow.",
        "<b>The thing is</b>, we've already spent the whole budget for this month.",
        "She's nice and all, but <b>the thing is</b>, she's never on time.",
        "<b>At the end of the day</b>, it's your decision, not theirs.",
        "We can argue about it, but <b>at the end of the day</b>, the customer's always right.",
        "<b>At the end of the day</b>, all that matters is that everyone got home safe.",
        "<b>I guess</b> you're right. I hadn't thought of it that way.",
        "We could just order pizza, <b>I guess</b>.",
        "<b>I guess</b> I'll go if everyone else is going.",
        "<b>As far as I'm concerned</b>, the matter's settled.",
        "He can do whatever he wants, <b>as far as I'm concerned</b>.",
        "<b>As far as I'm concerned</b>, you did nothing wrong.",
        "<b>The way I see it</b>, we've got nothing to lose by trying.",
        "<b>The way I see it</b>, they're the ones who owe you an apology.",
        "You can quit or you can stay and fight \u2014 <b>the way I see it</b>, those are your options.",
        "<b>I feel like</b> we should just leave early to beat the traffic.",
        "Honestly, <b>I feel like</b> she's not telling us everything.",
        "<b>I feel like</b> this color works better than the other one.",
        "<b>I'd say</b> it's about a two-hour drive, give or take.",
        "<b>I'd say</b> she's the best candidate we've interviewed so far.",
        "Is it worth it? <b>I'd say</b> so, yeah.",
        "<b>Don't get me wrong</b>, I like him \u2014 I just wouldn't want to work with him.",
        "The trip was great, <b>don't get me wrong</b>, but I was exhausted by the end.",
        "<b>Don't get me wrong</b>, the food's good; it's just overpriced.",
        "<b>Not gonna lie</b>, I completely forgot we had plans tonight.",
        "That test was brutal, <b>not gonna lie</b>.",
        "<b>Not gonna lie</b>, I'm kind of nervous about tomorrow.",
        "<b>The bottom line is</b>, we can't afford it right now.",
        "Look, <b>the bottom line is</b> they need this done by Friday.",
        "<b>The bottom line is</b>, if it makes you happy, do it.",
        "...and that's the whole saga with my landlord. <b>Anyway</b>, how was your weekend?",
        "I could go on about it forever, but <b>anyway</b>, the point is we got it done.",
        "<b>Anyway</b>, I should let you go \u2014 I know you're swamped.",
        "<b>By the way</b>, did you ever hear back from the dentist?",
        "Oh, <b>by the way</b>, Sarah says hi.",
        "I fixed the printer, <b>by the way</b>, so you're good to go.",
        "You're flying to Chicago? <b>Speaking of which</b>, is your passport still valid?",
        "We're going to Dana's this weekend \u2014 <b>speaking of which</b>, did you ever give her back that dish?",
        "He brought up the budget \u2014 <b>speaking of which</b>, did we ever pay that invoice?",
        "Oh, <b>that reminds me</b> \u2014 I still owe you twenty bucks.",
        "<b>That reminds me</b>, we need to call your mom back.",
        "You mentioned the gym? <b>That reminds me</b>, my membership's about to expire.",
        "We got lost, the car broke down... <b>long story short</b>, we never made it to the wedding.",
        "<b>Long story short</b>, I quit, and I've never been happier.",
        "There was a whole mix-up with the tickets, but <b>long story short</b>, we got in for free.",
        "The hotel was pricey. <b>That said</b>, the view was unbelievable.",
        "I'm not a huge fan of his music. <b>That said</b>, the concert was actually great.",
        "It's a lot of work. <b>That said</b>, I think it's worth it.",
        "We can drive or take the train \u2014 <b>either way</b>, we'll be there by six.",
        "Maybe he forgot, maybe he's just busy. <b>Either way</b>, I'm not waiting around.",
        "You can pay now or later. <b>Either way</b> works for me.",
        "'I just don't feel like going out tonight.' 'Yeah, <b>fair enough</b>.'",
        "You don't want to lend him the car? <b>Fair enough</b>, it's your call.",
        "'I'd rather not get into it.' '<b>Fair enough</b>, no pressure.'",
        "'We're leaving early to beat traffic.' 'Yeah, that <b>makes sense</b>.'",
        "<b>Makes sense</b> \u2014 no point paying for something you won't use.",
        "Oh okay, that actually <b>makes sense</b> now that you explain it.",
        "'Sorry I'm late!' '<b>No worries</b>, we just got here too.'",
        "'Thanks so much for helping.' '<b>No worries</b>, happy to.'",
        "If you can't make it, <b>no worries</b> \u2014 we'll catch up another time.",
        "'You coming Friday?' '<b>For sure</b>, wouldn't miss it.'",
        "'This place is way better than the old one.' '<b>For sure</b>.'",
        "<b>For sure</b>, I'll send that over first thing tomorrow.",
        "That movie was way too long, <b>right?</b>",
        "We said we'd meet at noon, <b>right?</b>",
        "It's kind of weird that he never replied, <b>right?</b>",
        "'So if we leave now, we skip the whole crowd.' '<b>Exactly</b>.'",
        "'He's not lazy, he's just burned out.' '<b>Exactly</b>, that's what I keep saying.'",
        "'You think we should wait for the sale?' '<b>Exactly</b> my point.'",
        "'This weather is insane.' '<b>I know, right?</b> I had to change twice today.'",
        "'That episode was so good.' '<b>I know, right?!</b>'",
        "'He totally deserved that promotion.' '<b>I know, right?</b> Finally.'",
        "'We should definitely do this again.' '<b>Totally</b>.'",
        "'It felt kind of rushed, didn't it?' '<b>Totally</b>, I noticed that too.'",
        "'You get why I'm annoyed, right?' '<b>Totally</b>.'",
        "'Just hit save before you close it.' '<b>Gotcha</b>.'",
        "'So the meeting moved to three.' '<b>Gotcha</b>, I'll update my calendar.'",
        "'Turn left after the gas station.' 'Okay, <b>gotcha</b>.'"
      ]
    },
    {
      id: "work-office",
      name: "Work / Office",
      lines: [
        "Hey, let's <b>touch base</b> early next week once you've heard back from the client.",
        "I just wanted to <b>touch base</b> and see where we are on the Q3 numbers.",
        "Can we <b>touch base</b> for five minutes before the standup?",
        "I'll <b>loop you in</b> on the thread so you can see what marketing decided.",
        "Let me <b>loop in</b> Sarah since she owns that account.",
        "Thanks for <b>looping me in</b> - I hadn't seen any of this.",
        "Let's park this for now and <b>circle back</b> after lunch.",
        "I'll <b>circle back</b> with you once I get the budget approved.",
        "Can we <b>circle back</b> to your point about staffing before we wrap up?",
        "Just <b>following up</b> on my email from last week - any thoughts?",
        "I'll <b>follow up</b> with the vendor to lock down a firm date.",
        "Did anyone ever <b>follow up</b> on that support ticket?",
        "Feel free to <b>reach out</b> if you have any questions.",
        "I'll <b>reach out</b> to IT and see if they can reset your access.",
        "A recruiter <b>reached out</b> to me on LinkedIn last week.",
        "Just wanted to <b>give you a heads-up</b> that the client's coming in at 2.",
        "Thanks for the <b>heads-up</b> - I'll get it done before then.",
        "Quick <b>heads-up</b>: the numbers go out to the exec team tomorrow morning.",
        "Nothing confirmed yet, but I'll <b>keep you posted</b>.",
        "We're still waiting on legal - I'll <b>keep you posted</b> as I hear more.",
        "<b>Keep me posted</b> on how the interview goes, okay?",
        "Make sure Dave stays <b>in the loop</b> on any pricing changes.",
        "Just keeping you <b>in the loop</b> - we pushed the launch to Friday.",
        "Can you keep me <b>in the loop</b> on where this lands?",
        "If you see anything off in the report, just <b>flag it</b> for me.",
        "I <b>flagged it</b> to my manager but haven't heard back yet.",
        "Good catch - I'll <b>flag it</b> with the dev team this morning.",
        "Let me check with finance and <b>get back to you</b> by end of day.",
        "Sorry for the delay - I'll <b>get back to you</b> first thing tomorrow.",
        "She said she'd <b>get back to me</b>, but it's been a week now.",
        "<b>Let me know</b> if that time works for you.",
        "<b>Let me know</b> what you think and I'll make the changes.",
        "Any questions, just <b>let me know</b>.",
        "<b>Shoot me an email</b> with the details and I'll take a look.",
        "If you need anything while I'm out, just <b>shoot me a message</b>.",
        "<b>Shoot me an email</b> whenever you get a chance - no rush.",
        "Just <b>checking in</b> to see if you had a chance to review the draft.",
        "Hey, <b>checking in</b> on the status of that invoice.",
        "Wanted to <b>check in</b> before the weekend - are we still on track?",
        "I'd love to help, but I've got a lot <b>on my plate</b> right now.",
        "Can this wait till next week? I've got too much <b>on my plate</b> to even look at it today.",
        "What's <b>on your plate</b> this week? Anything I can take off you?",
        "I'm really sorry, I <b>dropped the ball</b> on sending that invoice.",
        "We can't afford to <b>drop the ball</b> on this client.",
        "Honestly, marketing <b>dropped the ball</b> on this one. Nobody followed up with the leads.",
        "While Dana's on leave, we'll all need to <b>pick up the slack</b>.",
        "Thanks for <b>picking up the slack</b> last week. I was totally swamped.",
        "If one person's out, someone else has to <b>pick up the slack</b>.",
        "I use a checklist to <b>stay on top of</b> my deadlines.",
        "You've got to <b>stay on top of</b> your emails or they get out of hand.",
        "She's really good at <b>staying on top of</b> the project timeline.",
        "Don't worry about the deployment, I'm <b>on top of it</b>.",
        "The client asked for an update, but we're already <b>on top of it</b>.",
        "Good, sounds like you're <b>on top of it</b>.",
        "I just don't have the <b>bandwidth</b> to take on another project this quarter.",
        "Do you have the <b>bandwidth</b> to help me with this by Friday?",
        "Let's revisit it next month when the team has more <b>bandwidth</b>.",
        "I'm <b>juggling a few things</b> right now, so give me an hour.",
        "She's <b>juggling</b> three projects and onboarding a new hire at the same time.",
        "Sorry for the slow reply, I've been <b>juggling</b> a lot lately.",
        "Let's <b>get the ball rolling</b> on hiring before the holidays.",
        "I sent the kickoff email just to <b>get the ball rolling</b>.",
        "Once legal signs off, we can <b>get the ball rolling</b>.",
        "Don't worry about the printer, I'll <b>take care of it</b>.",
        "Can you <b>take care of</b> the catering for the offsite?",
        "It's already <b>taken care of</b>.",
        "Let's put the redesign on the <b>back burner</b> until Q3.",
        "That idea's been on the <b>back burner</b> for months.",
        "We had to move it to the <b>back burner</b> when the outage hit.",
        "I'll <b>follow up</b> with them if we don't hear back by Thursday.",
        "Just <b>following up on</b> my last email about the contract.",
        "Thanks for the meeting. I'll send a quick <b>follow-up</b> with next steps.",
        "We're a little <b>behind schedule</b> on the launch, so I might need another day or two.",
        "Honestly, the whole project's been <b>behind schedule</b> since the vendor dropped out.",
        "If we don't get sign-off today, we'll fall even further <b>behind schedule</b>.",
        "We're still <b>on track</b> to ship by Friday.",
        "Just wanted to confirm we're <b>on track</b> for the end-of-quarter numbers.",
        "The redesign slipped, but everything else is <b>on track</b>.",
        "It's <b>crunch time</b> now \u2014 everything ships Monday, so heads down this week.",
        "We're heading into <b>crunch time</b>, so let's punt anything non-urgent to next sprint.",
        "I know it's <b>crunch time</b>, but don't burn yourselves out.",
        "Can we <b>push back</b> the deadline to Thursday? The data came in late.",
        "They ended up <b>pushing back</b> the launch two weeks.",
        "Let's <b>push back</b> our one-on-one to the afternoon.",
        "It came <b>down to the wire</b>, but we submitted the proposal with five minutes to spare.",
        "This is going <b>down to the wire</b> \u2014 QA's still finding bugs an hour before release.",
        "Every quarter it's the same thing, we're always <b>down to the wire</b>.",
        "Good news \u2014 we're actually <b>ahead of schedule</b> on the migration.",
        "The contractor finished the buildout a week <b>ahead of schedule</b>.",
        "If everything holds, we'll wrap this up <b>ahead of schedule</b>.",
        "We're so close on this deal \u2014 let's do whatever it takes to <b>get it across the finish line</b>.",
        "One more approval and we can <b>get this across the finish line</b>.",
        "Thanks, everyone, for helping <b>get it across the finish line</b> before the holidays.",
        "I can't really talk right now, I'm <b>up against a deadline</b>.",
        "The team's <b>up against a deadline</b> on the RFP, so bear with us.",
        "We're really <b>up against it</b> this week with two launches.",
        "It's a pretty <b>tight deadline</b>, but I think we can make it work.",
        "They gave us a really <b>tight deadline</b> \u2014 end of day Friday.",
        "That's a really <b>tight deadline</b> \u2014 I'd want to check with the team before I commit.",
        "If we ship the beta first, that'll <b>buy us some time</b> on the full release.",
        "Can you stall the client for a day? Just <b>buy me some time</b>.",
        "Pushing the demo back <b>buys us a little time</b> to fix the bugs.",
        "Can you send me the deck <b>by end of day</b>?",
        "I'll have the numbers to you <b>by EOD</b>.",
        "Let's aim to wrap this up <b>by end of day</b> tomorrow.",
        "Hey, you wanna <b>grab lunch</b> after the standup?",
        "We usually <b>grab lunch</b> around noon if you feel like joining.",
        "I'm starving\u2014let's <b>grab lunch</b> before the one o'clock.",
        "Can you <b>cover for</b> me Friday? I've got a doctor's appointment.",
        "Thanks for <b>covering for</b> me while I was out sick.",
        "Someone needs to <b>cover for</b> Dana at the front desk during her break.",
        "I'll be <b>out of office</b> next week, so loop in Priya on anything urgent.",
        "Did you set your <b>out of office</b> before you left?",
        "Heads-up, I'm <b>out of office</b> Thursday and Friday for a conference.",
        "I <b>work from home</b> on Fridays.",
        "Can I <b>work from home</b> tomorrow? The plumber's coming.",
        "Half the team <b>works from home</b> now, so the office is pretty empty.",
        "Just <b>a heads-up</b>\u2014the client's running about fifteen minutes late.",
        "Thanks for the <b>heads-up</b> about the fire drill.",
        "Give me a <b>heads-up</b> if the meeting time moves.",
        "Let's <b>wrap up</b> here\u2014we're already over time.",
        "I just need to <b>wrap up</b> a couple of emails and then I'm free.",
        "Are you almost done, or still <b>wrapping up</b>?"
      ]
    },
    {
      id: "tech-software-development",
      name: "Tech / Software Development",
      lines: [
        "Tests are green and QA signed off, so let's just <b>ship it</b>.",
        "Honestly it's good enough for v1 \u2014 <b>ship it</b> and we'll iterate.",
        "Stop polishing the CSS, man, just <b>ship it</b>.",
        "Please don't <b>push to prod</b> on a Friday afternoon.",
        "We <b>pushed to prod</b> around two and the error rate spiked instantly.",
        "Who <b>pushed to prod</b> without running the migration first?",
        "Can you review this so I can <b>merge the PR</b> before standup?",
        "I'll <b>merge the PR</b> once CI passes.",
        "Don't <b>merge the PR</b> yet \u2014 I still have a couple of comments.",
        "Let me <b>spin up</b> a staging environment so you can test it.",
        "We can <b>spin up</b> a couple more instances if traffic gets crazy.",
        "I <b>spun up</b> a quick Postgres container to reproduce the bug.",
        "The deploy broke checkout, so we had to <b>roll back</b>.",
        "If anything looks off, just <b>roll back</b> to the last release.",
        "We <b>rolled back</b> within five minutes, so most users never noticed.",
        "The payment bug was critical, so we <b>pushed a hotfix</b> overnight.",
        "Can we <b>push a hotfix</b> for this, or does it have to wait for the release?",
        "It's a one-line change \u2014 I'll just <b>push a hotfix</b> real quick.",
        "If it's not on the board, <b>open a ticket</b> so we don't lose track of it.",
        "I'll <b>open a ticket</b> for the flaky test and assign it to myself.",
        "Did you <b>open a ticket</b> for that, or is it just buried in Slack somewhere?",
        "We're planning to <b>cut a release</b> on Thursday if everything stays stable.",
        "Once this PR lands, I'll <b>cut a release</b> and tag it.",
        "Let's <b>cut a release</b> candidate and let QA hammer on it.",
        "We're in a <b>code freeze</b> until the launch, so no new features.",
        "<b>Code freeze</b> starts Monday \u2014 get your PRs merged this week.",
        "Is this a hard <b>code freeze</b>, or can we still land bug fixes?",
        "We're going to <b>roll out</b> the new dashboard to 10% of users first.",
        "Let's <b>roll out</b> the feature gradually and watch the metrics.",
        "They <b>rolled out</b> the update to everyone at once and it melted the servers.",
        "I went through the diff \u2014 <b>looks good to me</b>, ship it.",
        "Left one tiny nit, but otherwise it <b>looks good to me</b>.",
        "Approved. <b>Looks good to me</b>.",
        "Run the tests locally first so you don't <b>break the build</b>.",
        "Someone <b>broke the build</b> on main \u2014 nobody can deploy until it's green.",
        "My bad, I <b>broke the build</b>; pushing a fix now.",
        "CI's green and QA signed off \u2014 we're <b>good to go</b> for the deploy.",
        "Once you rebase on main, you should be <b>good to go</b>.",
        "Migration ran clean, so we're <b>good to go</b>.",
        "I <b>put up a PR</b> \u2014 can someone take a look?",
        "Go ahead and <b>put up a PR</b> and tag me as a reviewer.",
        "I'll <b>put up a PR</b> after lunch once I clean up the commits.",
        "The happy path works fine, but we're not handling the <b>edge case</b> where the list is empty.",
        "Most of these bugs are just weird <b>edge cases</b> nobody thought to test.",
        "What happens if the timezone offset is negative? That's an <b>edge case</b> we need to cover.",
        "If the config file is missing, it should just <b>throw an error</b> instead of failing silently.",
        "Why is this <b>throwing an error</b>? The input looks totally valid to me.",
        "Don't let it crash the whole app, just <b>throw an error</b> and let the caller handle it.",
        "I spent all afternoon trying to <b>track down</b> where this null was coming from.",
        "It took us two days to <b>track down</b> the memory leak.",
        "Can you help me <b>track down</b> why the page is loading so slowly?",
        "I can't <b>reproduce the issue</b> locally, it only happens in production.",
        "Do you have steps to <b>reproduce the issue</b>? I'm not seeing it on my end.",
        "Once we could <b>reproduce the issue</b> consistently, the fix was pretty quick.",
        "The <b>root cause</b> turned out to be a caching bug, not the API like we thought.",
        "Let's not just patch the symptom, we need to find the <b>root cause</b>.",
        "We're still doing the <b>root cause</b> analysis, but it looks like a race condition.",
        "This <b>flaky test</b> fails maybe one in ten runs for no reason.",
        "Can someone look at that <b>flaky test</b> in CI? It keeps blocking merges.",
        "I hate <b>flaky tests</b>, you never know if the failure is real or not.",
        "Something's off in prod, let me <b>check the logs</b>.",
        "Did you <b>check the logs</b>? There might be a stack trace in there.",
        "I <b>checked the logs</b> and there's a bunch of timeout errors around 3am.",
        "I've <b>narrowed it down</b> to either the auth service or the database.",
        "Let's add some logging so we can <b>narrow it down</b>.",
        "We <b>narrowed it down</b> to a single commit that introduced the bug.",
        "Just paste the full <b>stack trace</b>, I can't tell what's failing from that.",
        "The <b>stack trace</b> points to line 42 in the parser.",
        "There's no <b>stack trace</b>, it just hangs, which makes it way harder to debug.",
        "I <b>went down a rabbit hole</b> debugging the linter and completely forgot what I was actually trying to fix.",
        "Careful, that part of the codebase is a total <b>rabbit hole</b>.",
        "I don't want to <b>go down a rabbit hole</b> on this, let's just ship a quick fix.",
        "The <b>happy path</b> works, but everything breaks the moment there's bad input.",
        "We only tested the <b>happy path</b>, so of course it fell over in production.",
        "Let's get the <b>happy path</b> working first, then handle the error cases.",
        "Before we deploy, let me just do a quick <b>sanity check</b> on the config.",
        "Can you run a <b>sanity check</b> to make sure the data actually loaded?",
        "Just as a <b>sanity check</b>, did you save the file before rebuilding?",
        "I don't get it, it <b>works on my machine</b>.",
        "'<b>Works on my machine</b>' isn't going to help the customer, though.",
        "Classic - it <b>works on my machine</b> but blows up in CI.",
        "I'll bring it up at <b>standup</b> tomorrow morning.",
        "Can you drop your update in Slack? I'm gonna miss <b>standup</b> today.",
        "We spent twenty minutes on one ticket \u2014 <b>standup</b> is supposed to be fifteen, tops.",
        "Let's <b>sync up</b> after lunch and figure out the API changes.",
        "Can we <b>sync up</b> real quick before you push that?",
        "We should <b>sync up</b> with design before we build the whole flow.",
        "We shipped it fast, but we took on a ton of <b>tech debt</b>.",
        "Half of this sprint is just paying down <b>tech debt</b>.",
        "That workaround is fine for now \u2014 just log it as <b>tech debt</b> so we don't forget.",
        "This started as a login page and now it's a whole dashboard \u2014 classic <b>scope creep</b>.",
        "We need to watch out for <b>scope creep</b> on this one.",
        "Every 'small' request adds up; that's how <b>scope creep</b> kills a deadline.",
        "I can't finish the feature \u2014 staging being down is a <b>blocker</b>.",
        "Any <b>blockers</b> on your end?",
        "Waiting on the API key is my only <b>blocker</b> right now.",
        "Good discussion, but let's <b>take it offline</b> \u2014 we're eating into everyone's time.",
        "That's a rabbit hole; can you two <b>take it offline</b> and report back?",
        "We'll <b>take this offline</b> and loop the rest of you in later.",
        "Let's knock out the <b>low-hanging fruit</b> first, then tackle the hard stuff.",
        "Fixing those typos is <b>low-hanging fruit</b> \u2014 do it before the demo.",
        "There's a lot of <b>low-hanging fruit</b> in the onboarding flow if we want quick wins.",
        "Dark mode is a <b>nice-to-have</b>, not a must-have for launch.",
        "Let's separate the <b>nice-to-haves</b> from the things we actually need.",
        "Sure, animations would be nice, but that's a <b>nice-to-have</b> \u2014 ship the core flow first.",
        "Before we start coding, let's make sure we're <b>on the same page</b> about the requirements.",
        "Quick recap so everyone's <b>on the same page</b>.",
        "I thought we were <b>on the same page</b>, but you built something totally different.",
        "Let's <b>loop in</b> Sarah \u2014 she owns that service.",
        "Can you <b>loop me in</b> on the thread when you hear back?",
        "I should've <b>looped</b> design <b>in</b> earlier \u2014 that's on me.",
        "<b>Ping</b> me when the build's green and I'll deploy.",
        "I'll <b>ping</b> her on Slack real quick.",
        "Just <b>ping</b> the channel if you get stuck."
      ]
    },
    {
      id: "meetings",
      name: "Meetings",
      lines: [
        "Okay, I think everyone's here, so <b>let's get started</b>.",
        "It's a little past two, so <b>let's get started</b> and we'll catch the others up later.",
        "Alright, <b>let's get started</b> \u2014 we've got a lot to cover today.",
        "<b>Thanks everyone for joining</b> \u2014 I know it's early on the West Coast.",
        "<b>Thanks everyone for joining</b> today, especially on such short notice.",
        "Hey all, <b>thanks everyone for joining</b>. Let's give it a sec for a couple more people to hop on.",
        "We're short on time, so <b>let's dive in</b>.",
        "No need for long intros \u2014 <b>let's dive in</b>.",
        "Great, everyone's got the deck in front of them? <b>Let's dive in</b>.",
        "<b>Let's kick things off</b> with a quick update from marketing.",
        "Alright, <b>let's kick things off</b> \u2014 Sarah, do you want to start?",
        "To save time, <b>let's kick things off</b> with the numbers and take questions after.",
        "Let's <b>go around the room</b> and have everyone give a quick status update.",
        "Before we start, let's <b>go around the room</b> so the new folks can introduce themselves.",
        "We'll <b>go around the room</b>, and if you're remote just jump in when I call your name.",
        "For anyone who missed last week, here's a <b>quick recap</b>.",
        "Let me give you a <b>quick recap</b> of where we landed.",
        "<b>Quick recap</b> before we move on: we agreed to push the launch to March.",
        "<b>For those just joining</b>, we're on the second agenda item.",
        "<b>For those just joining us</b>, I'll repeat the question that came up.",
        "<b>For those just joining</b>, we wrapped up the budget discussion a minute ago.",
        "<b>First on the agenda</b> is the Q3 roadmap.",
        "So, <b>first on the agenda</b> \u2014 let's talk about the budget.",
        "We've got three things today; <b>first up on the agenda</b> is hiring.",
        "<b>Let's give it a couple minutes</b> for people to trickle in.",
        "It's just us so far \u2014 <b>let's give it a couple minutes</b>.",
        "<b>Let's give it a couple minutes</b> and then we'll get going.",
        "Before we start, just <b>a couple of housekeeping items</b> \u2014 this call is being recorded.",
        "<b>A couple of housekeeping items</b> first: mics on mute, questions in the chat.",
        "Quick note, <b>a couple of housekeeping items</b> and then we'll jump in.",
        "<b>Can everyone hear me okay?</b> Great, let's get going.",
        "Sorry, one sec \u2014 <b>can everyone hear me okay</b> now?",
        "<b>Can everyone hear me okay?</b> Give me a thumbs up if the audio's good.",
        "Sorry, <b>let me jump in</b> here real quick \u2014 I think we're missing one thing.",
        "Can I <b>jump in</b>? I've actually dealt with this exact issue before.",
        "Before we move on, <b>let me jump in</b> with a quick clarification.",
        "Just to <b>piggyback on that</b>, we saw the same pattern in the Q2 numbers.",
        "Can I <b>piggyback on</b> what Dana said? It ties into the timeline.",
        "I want to <b>piggyback on that</b> point about staffing before we move on.",
        "<b>To build on that</b>, I'd suggest we also loop in the design team.",
        "Yeah, and <b>building on</b> what Marcus said, the deadline is actually flexible.",
        "Just <b>to build on that</b> \u2014 the same logic applies to the mobile version.",
        "<b>To your point</b>, I think we should test it before we launch.",
        "And <b>to your point</b> earlier, the budget just won't stretch that far.",
        "Right, <b>to your point</b>, that's exactly why we paused the rollout.",
        "Let me <b>play devil's advocate</b> for a second \u2014 what if customers hate it?",
        "Just to <b>play devil's advocate</b>, is anyone actually asking for this feature?",
        "I'll <b>play devil's advocate</b> here: how do we know the data's reliable?",
        "Good point, but <b>let's park that</b> and finish the budget first.",
        "Can we <b>park that</b> for now? We're running low on time.",
        "I'm going to <b>park that</b> idea \u2014 it really deserves its own meeting.",
        "<b>Let's not get sidetracked</b> \u2014 we still have three items to cover.",
        "That's interesting, but <b>let's not get sidetracked</b> here.",
        "I don't want us to <b>get sidetracked</b>, so let's finish this piece first.",
        "Sorry, John \u2014 <b>you're on mute</b>.",
        "We can't hear you, I think <b>you're on mute</b>.",
        "<b>You're on mute</b>! ... There you go, now we've got you.",
        "Hey, <b>can you hear me</b> okay?",
        "Sorry, I had connection issues \u2014 <b>can you hear me</b> now?",
        "<b>Can everyone hear me</b> alright before I share my screen?",
        "So we ship Tuesday, then review Thursday \u2014 <b>does that make sense</b>?",
        "I know that was a lot. <b>Does that make sense</b> so far?",
        "We're cutting scope, not the deadline. <b>Does that make sense</b>?",
        "Can we <b>take a step back</b> and ask why we're even doing this?",
        "Let me <b>take a step back</b> and give some context first.",
        "I think we need to <b>take a step back</b> here \u2014 we're solving the wrong problem.",
        "Oh, sorry \u2014 <b>go ahead</b>, you were saying?",
        "No no, <b>go ahead</b>, finish your thought.",
        "Did you have a question? <b>Go ahead</b>.",
        "<b>Quick question</b> \u2014 is this the final version or a draft?",
        "Sorry, <b>quick question</b> before we move on.",
        "I've got a <b>quick question</b> about the timeline.",
        "Okay, before we log off, let me read back the <b>action items</b> so we're all clear on who's doing what.",
        "I'll drop the <b>action items</b> in the Slack channel with a name next to each one.",
        "We've got three <b>action items</b> coming out of this \u2014 Priya, the first two are yours.",
        "So what are the <b>next steps</b> here? Who's doing what by when?",
        "Let's talk <b>next steps</b> real quick and then we can all get out of here.",
        "Great discussion \u2014 I'll write up the <b>next steps</b> and send them around.",
        "Alright, we're coming up on the hour, so <b>let's wrap up</b>.",
        "<b>Let's wrap up</b> here \u2014 I know a few of you have another call at the top of the hour.",
        "Before we <b>wrap up</b>, does anyone have anything else they want to raise?",
        "We're running low on time, so <b>let's table this</b> and pick it up next week.",
        "I'm going to <b>table this</b> discussion \u2014 it's bigger than what we can cover today.",
        "Can we <b>table this</b> for now and stay focused on the launch?",
        "This is a great debate but it only affects us two \u2014 <b>let's take this offline</b>.",
        "We're getting into the weeds here, so let's <b>take this offline</b> and report back.",
        "I'll <b>take this offline</b> with Dev and we'll come back with a recommendation.",
        "Let's <b>put a pin in it</b> and revisit after the demo.",
        "Good question \u2014 can we <b>put a pin in that</b> and get to it at the end?",
        "I'll <b>put a pin in this</b> so we don't lose it, but let's keep moving for now.",
        "Okay, that's everything from me \u2014 <b>any last questions</b> before we drop off?",
        "<b>Any last questions</b>, or are we good to wrap?",
        "Before I let you go, <b>any last questions</b> on the rollout?",
        "So <b>who owns this</b>? I want one name on it, not a whole team.",
        "Great, that's decided \u2014 but <b>who owns</b> the follow-up?",
        "Let's be clear on <b>who owns this</b> before we move on.",
        "I'll <b>keep you in the loop</b> as things develop with the client.",
        "Don't worry \u2014 I'll <b>keep you in the loop</b> on any changes to the timeline.",
        "Can you <b>keep me in the loop</b> on that thread? I want to see how it lands."
      ]
    },
    {
      id: "making-plans",
      name: "Making Plans",
      lines: [
        "Hey, <b>do you wanna grab</b> a coffee after class?",
        "<b>Do you wanna grab</b> lunch sometime this week?",
        "We're all heading out later \u2014 <b>do you wanna grab</b> a drink with us?",
        "<b>How about</b> Saturday afternoon instead?",
        "<b>How about</b> we just order in and watch a movie?",
        "I can't do Friday. <b>How about</b> Sunday?",
        "<b>Are you free</b> this weekend? I was thinking we could go hiking.",
        "<b>Are you free</b> around seven, or is that too early?",
        "Hey, <b>are you free</b> Thursday night? There's a show I want to catch.",
        "<b>Do you want to hang out</b> this weekend?",
        "We haven't seen you in ages \u2014 <b>do you want to hang out</b> Friday?",
        "<b>Do you want to hang out</b> later, or are you busy?",
        "<b>Are you up for</b> grabbing dinner tonight?",
        "I'm thinking of going for a run \u2014 you <b>up for</b> it?",
        "Is everyone <b>up for</b> trying that new Thai place?",
        "<b>What are you up to</b> later? Wanna get food?",
        "<b>What are you up to</b> this weekend \u2014 any plans?",
        "Hey, <b>what are you up to</b> tonight?",
        "<b>We should</b> grab lunch sometime and catch up.",
        "<b>We should</b> totally go see that movie this weekend.",
        "<b>We should</b> do this more often!",
        "<b>Why don't we</b> just meet at the restaurant?",
        "<b>Why don't we</b> do something outdoors while the weather's nice?",
        "<b>Why don't we</b> make it a bit later, like eight?",
        "<b>Let's just</b> stay in and order pizza.",
        "<b>Let's just</b> meet there \u2014 it's easier than driving together.",
        "I'm tired. <b>Let's just</b> keep it low-key tonight.",
        "We should grab coffee and <b>catch up</b> soon.",
        "Let's <b>catch up</b> this week \u2014 it's been forever.",
        "I'd love to <b>catch up</b> \u2014 are you around Saturday?",
        "You should <b>come over</b> Friday \u2014 we're having some people over.",
        "Do you want to <b>come over</b> and watch the game?",
        "Feel free to <b>come over</b> whenever you're done with work.",
        "<b>Do you feel like</b> getting out of the house tonight?",
        "I kind of <b>feel like</b> pizza \u2014 you in?",
        "<b>Do you feel like</b> going for a walk, or should we just chill?",
        "<b>Are you down for</b> a road trip this weekend?",
        "There's a party Saturday \u2014 you <b>down for</b> it?",
        "I'm totally <b>down for</b> whatever, honestly \u2014 you pick.",
        "\"How about we grab lunch around noon?\" \"Yeah, noon <b>works for me</b>.\"",
        "Tuesday <b>works for me</b> if it works for everyone else.",
        "Honestly, any time after 5 <b>works for me</b>, so just pick a slot.",
        "I was thinking we meet at 3. <b>Does that work for you?</b>",
        "Let's do Saturday morning \u2014 <b>does that work for you</b>, or is that too early?",
        "I can swing by after work. <b>Does that work for you</b> guys?",
        "\"I'll text you the address when I'm leaving.\" \"<b>Sounds good.</b>\"",
        "<b>Sounds good</b> to me \u2014 see you there at 7.",
        "\"Let's just meet at the entrance.\" \"Yeah, <b>sounds good</b>, see you then.\"",
        "Hey, <b>are we still on for</b> dinner tonight?",
        "Just checking \u2014 <b>are we still on for</b> the gym tomorrow morning?",
        "<b>Are we still on for</b> Friday, or did something change on your end?",
        "\"We're doing a beach trip Sunday.\" \"Oh, <b>count me in!</b>\"",
        "If there's pizza involved, <b>count me in</b>.",
        "<b>Count me in</b> for the concert \u2014 just tell me how much I owe you for the ticket.",
        "\"Wanna check out that new taco place?\" \"Yeah, <b>I'm down</b>.\"",
        "<b>I'm down</b> for whatever \u2014 you pick the movie.",
        "\"A few of us are hiking Saturday.\" \"<b>I'm so down</b>, what time?\"",
        "I need to check with my wife first \u2014 <b>let me get back to you</b> tonight.",
        "\"Can you make the 10am?\" \"<b>Let me get back to you</b> once I see my calendar.\"",
        "I'm not sure I'm free that weekend. <b>Let me get back to you</b> by Friday, is that okay?",
        "I might be able to make it \u2014 <b>I'll let you know</b> closer to the day.",
        "\"Are you coming to the party?\" \"Not sure yet, <b>I'll let you know</b>.\"",
        "Once I hear back from work about my shift, <b>I'll let you know</b>.",
        "I'll <b>pencil you in</b> for Thursday and confirm once I know for sure.",
        "Let me <b>pencil it in</b> \u2014 nothing's set in stone yet.",
        "\"Can we say around 2?\" \"Sure, I'll <b>pencil you in</b> and we'll firm it up later.\"",
        "Hey, I'm so sorry, but <b>something came up</b> and I can't make it tonight.",
        "<b>Something came up</b> at work, so I might be a little late \u2014 go ahead and order.",
        "We had to cancel Sunday because <b>something came up</b> with the kids.",
        "I'm wiped out tonight \u2014 can I <b>take a rain check</b> on drinks?",
        "Mind if I <b>take a rain check</b>? I promise we'll do it next week.",
        "\"Movie tonight?\" \"I've gotta <b>take a rain check</b>, but text me next time you go.\"",
        "Can we <b>push it back</b> an hour? I'm stuck in traffic.",
        "Let's <b>push it back</b> to next week \u2014 this week's crazy for me.",
        "They asked to <b>push it back</b> to 3 instead of 1, if that's cool with you."
      ]
    },
    {
      id: "socializing",
      name: "Socializing",
      lines: [
        "We should <b>hang out</b> this weekend, it's been forever.",
        "They're just <b>hanging out</b> at Jake's place if you wanna swing by.",
        "You wanna come <b>hang out</b> for a bit? Nothing special going on.",
        "We're <b>having a few people over</b> Friday if you're free.",
        "I don't <b>have people over</b> much since the baby.",
        "They <b>had us over</b> for dinner last week and it was great.",
        "<b>Feel free to</b> bring someone if you want, the more the merrier.",
        "<b>Feel free to</b> grab whatever you want from the fridge.",
        "The pool's open, so <b>feel free to</b> jump in.",
        "There's beer in the cooler \u2014 <b>help yourself</b>.",
        "<b>Help yourself</b> to whatever's in the fridge, seriously.",
        "Snacks are on the table, everyone <b>help yourselves</b>!",
        "Come in, come in \u2014 <b>make yourself at home</b>.",
        "I'll be like five minutes; <b>make yourself at home</b>.",
        "<b>Make yourself at home</b>, there's coffee if you want some.",
        "We should <b>get together</b> soon \u2014 it's been way too long.",
        "They're having a little <b>get-together</b> at their place Saturday.",
        "Let's <b>get together</b> for coffee sometime next week.",
        "This was so fun \u2014 <b>thanks for having me</b>!",
        "We're gonna head out. <b>Thanks for having us</b>, everyone.",
        "<b>Thanks for having me</b>, dinner was amazing.",
        "Sure, bring your roommate too \u2014 <b>the more the merrier</b>!",
        "Can my cousins tag along? \u2014 Of course, <b>the more the merrier</b>.",
        "We've got plenty of food, so honestly <b>the more the merrier</b>.",
        "Hey! <b>Come on in</b>, everyone's in the kitchen.",
        "<b>Come on in</b>, don't worry about your shoes.",
        "There you are \u2014 <b>come on in</b>, let me take your coat.",
        "Welcome! <b>Can I get you anything</b> \u2014 water, coffee, a beer?",
        "Have a seat. <b>Can I get you anything</b> to drink?",
        "<b>Can I get you guys anything</b> before the movie starts?",
        "The invite says I can <b>bring a plus-one</b>, so do you wanna come?",
        "Am I allowed to <b>bring a plus-one</b> to the wedding?",
        "She's <b>bringing a plus-one</b> to the office party.",
        "I hate that first-meeting silence, so I usually crack a joke just to <b>break the ice</b>.",
        "They had everyone share one weird fact about themselves to <b>break the ice</b>.",
        "Somebody's gotta <b>break the ice</b> here, nobody's talking.",
        "I introduced her to my roommate and they totally <b>hit it off</b>.",
        "We met at a wedding and just <b>hit it off</b> right away.",
        "I thought it'd be awkward, but we really <b>hit it off</b>.",
        "You wanna <b>grab a drink</b> after this?",
        "We should <b>grab a drink</b> sometime and catch up.",
        "A bunch of us are gonna <b>grab a drink</b> downstairs, come with.",
        "I'm beat, I think I'm gonna <b>call it a night</b>.",
        "One more drink and then let's <b>call it a night</b>.",
        "It's almost 2 a.m., we should probably <b>call it a night</b>.",
        "We haven't had <b>a night out</b> in ages, let's do something Friday.",
        "It was supposed to be a chill dinner but it turned into a full <b>night out</b>.",
        "The girls are planning <b>a night out</b> for her birthday.",
        "Once he's had a couple drinks he becomes <b>the life of the party</b>.",
        "She's so outgoing, always <b>the life of the party</b>.",
        "Invite Marco, he's <b>the life of the party</b>.",
        "Grab a drink and go <b>mingle</b>, you don't know anyone yet.",
        "I'm gonna <b>mingle</b> a bit, I'll find you later.",
        "The whole point of these networking things is to <b>mingle</b>.",
        "I'm terrible at <b>small talk</b>, I never know what to say.",
        "We made <b>small talk</b> by the snack table for a few minutes.",
        "He skipped the <b>small talk</b> and got straight to the point.",
        "Barely anyone <b>showed up</b> to her party, it was kind of sad.",
        "He <b>showed up</b> two hours late like it was no big deal.",
        "Just <b>show up</b>, you don't need to bring anything.",
        "This party's dead, wanna <b>bail</b>?",
        "Sorry I <b>bailed</b> last night, I was exhausted.",
        "He said he'd come but he <b>bailed</b> on us again.",
        "Guess who I <b>ran into</b> at the party last night?",
        "I <b>ran into</b> an old coworker at the bar, totally random.",
        "If you <b>run into</b> Sarah, tell her I said hi.",
        "Am I allowed a <b>plus one</b>, or is it just me?",
        "She brought her boyfriend as her <b>plus one</b>.",
        "I don't have a date, so you can be my <b>plus one</b>."
      ]
    },
    {
      id: "problem-solving",
      name: "Problem Solving",
      lines: [
        "We were halfway through the migration when we <b>ran into a problem</b> with the old database.",
        "If you <b>run into any problems</b> during setup, just shoot me a message.",
        "I <b>ran into a bit of a problem</b> trying to get the two systems to talk to each other.",
        "We were on track to ship Friday, but we <b>hit a snag</b> with the payment integration.",
        "The remodel <b>hit a snag</b> when the inspector flagged the wiring.",
        "Everything was going great until we <b>hit a snag</b> with customs.",
        "Let's stop patching symptoms and figure out <b>the root of the problem</b>.",
        "Turns out <b>the root of the problem</b> was one misconfigured setting.",
        "Until we deal with <b>the root of the problem</b>, this is just going to keep happening.",
        "The approval step is the real <b>bottleneck</b> \u2014 everything just sits there waiting.",
        "We added more servers, but the database is still the <b>bottleneck</b>.",
        "Honestly, I think I'm the <b>bottleneck</b> here; I can't review everything fast enough.",
        "The salary's fine, but no remote work? That's a <b>dealbreaker</b> for me.",
        "It's a nice apartment, but the lack of parking is a <b>dealbreaker</b>.",
        "The bug itself isn't a <b>dealbreaker</b>, but we can't launch until it's fixed.",
        "You can get it for free, but <b>there's a catch</b> \u2014 you have to commit for a year.",
        "The plan works, but <b>there's a catch</b>: it only runs on the newest phones.",
        "It looks too good to be true, and sure enough, <b>there's a catch</b>.",
        "Sure, just 'stay calm and rewrite the whole thing' \u2014 <b>easier said than done</b>.",
        "Cutting costs sounds great, but it's <b>easier said than done</b> when everyone's already stretched.",
        "'Just talk to your boss about it.' Yeah, <b>easier said than done</b>.",
        "Whether that counts as a business expense is kind of a <b>gray area</b>.",
        "The rules don't really cover this case, so we're in a <b>gray area</b>.",
        "It's a legal <b>gray area</b>, so we should probably ask someone before we do it.",
        "Okay, let's address <b>the elephant in the room</b> \u2014 are we going to make the deadline or not?",
        "Nobody wanted to mention it, but the budget was <b>the elephant in the room</b> the whole meeting.",
        "Can we finally talk about <b>the elephant in the room</b>? The project is way over budget.",
        "That outage was bad, but honestly it's just <b>the tip of the iceberg</b>.",
        "The complaints we've seen are <b>the tip of the iceberg</b> \u2014 most people don't even bother reporting it.",
        "Fixing this one bug helps, but it's <b>the tip of the iceberg</b>.",
        "With so many tickets coming in, a few requests <b>fell through the cracks</b>.",
        "We need a better system so nothing <b>falls through the cracks</b>.",
        "Her case just <b>fell through the cracks</b> \u2014 nobody was assigned to follow up.",
        "I asked one question about the billing and it <b>opened a whole can of worms</b>.",
        "Let's not <b>open that can of worms</b> right before the release.",
        "Renaming the files sounds simple, but it <b>opens a real can of worms</b> with all the links.",
        "The supplier backing out really <b>threw a wrench in</b> our timeline.",
        "One person calling in sick can <b>throw a wrench into</b> the whole schedule.",
        "The new regulation <b>threw a wrench in the works</b> just as we were about to launch.",
        "Working from home is a <b>double-edged sword</b> \u2014 more freedom, but you never really log off.",
        "The publicity is a <b>double-edged sword</b>; it brings customers but also a lot of scrutiny.",
        "Automating it is a <b>double-edged sword</b> \u2014 faster, but harder to debug when it breaks.",
        "I don't know how the new system works yet, but give me an hour and I'll <b>figure it out</b>.",
        "We couldn't <b>figure out</b> why the app kept crashing until we checked the logs.",
        "Don't worry about who sits where, we'll <b>figure it out</b> when everyone shows up.",
        "We need to <b>come up with</b> a plan before the client call tomorrow.",
        "How did you <b>come up with</b> that solution so fast?",
        "I'm drawing a blank, I can't <b>come up with</b> anything better right now.",
        "We can't move the deadline, so we'll just have to <b>work around it</b>.",
        "The API doesn't support that yet, but there's a way to <b>work around</b> the limitation.",
        "One of the machines is down, but the team figured out how to <b>work around it</b> for now.",
        "There've been three outages this week and we need to <b>get to the bottom of</b> it.",
        "I don't know why the numbers don't match, but I'm going to <b>get to the bottom of</b> this.",
        "Let's talk to the team and <b>get to the bottom of</b> what actually happened.",
        "The deal is basically done, we just need to <b>iron out</b> a few details.",
        "There are still some bugs to <b>iron out</b> before we ship.",
        "Let's grab coffee and <b>iron out</b> who's doing what.",
        "Don't stress about the billing error, I'll call them and <b>sort it out</b>.",
        "You two need to <b>sort out</b> your differences before the meeting.",
        "There was a mix-up with the order, but we got it <b>sorted out</b>.",
        "Before we start, let's agree on a <b>game plan</b>.",
        "We went in without a <b>game plan</b> and it showed.",
        "Okay, what's our <b>game plan</b> for clearing the backlog?",
        "The usual fixes aren't working, so we need to <b>think outside the box</b>.",
        "I love that idea, that's really <b>thinking outside the box</b>.",
        "They hired her because she <b>thinks outside the box</b>.",
        "I still can't <b>wrap my head around</b> how this bug even happens.",
        "Give me a second to <b>wrap my head around</b> what you're proposing.",
        "It took me a while to <b>wrap my head around</b> the new pricing model.",
        "We <b>ran into</b> a few issues during last night's deployment.",
        "If you <b>run into</b> any problems, just message me.",
        "I <b>ran into</b> a wall trying to get the two systems to talk to each other.",
        "The prototype didn't work at all, so it's <b>back to the drawing board</b>.",
        "Client rejected all three designs, so it's <b>back to the drawing board</b>, I guess.",
        "That approach was a dead end, so we went <b>back to the drawing board</b>.",
        "There's a lot on our plate, but let's <b>tackle it</b> one thing at a time.",
        "I finally decided to just <b>tackle it</b> head-on instead of putting it off.",
        "The bug list looks scary, but we can <b>tackle it</b> if we prioritize."
      ]
    },
    {
      id: "emotions-opinions",
      name: "Emotions & Opinions",
      lines: [
        "I've been so <b>stressed out</b> this week - three deadlines and my car broke down.",
        "Don't get <b>stressed out</b> about the interview, you're totally ready.",
        "She's completely <b>stressed out</b> trying to plan the whole wedding by herself.",
        "After two years with no vacation, I'm totally <b>burnt out</b>.",
        "A lot of teachers are <b>burnt out</b> by the end of the school year.",
        "I love my job, but doing 12-hour days left me completely <b>burnt out</b>.",
        "I'm so <b>fed up with</b> this traffic - I'm going to start taking the train.",
        "She finally quit; she was just <b>fed up</b>.",
        "He's <b>fed up with</b> people showing up late to every meeting.",
        "Everyone's a little <b>on edge</b> waiting for the layoff news.",
        "Sorry I snapped - I've been <b>on edge</b> all day.",
        "The constant noise from the construction has me <b>on edge</b>.",
        "She's <b>freaking out</b> because she can't find her passport.",
        "Don't <b>freak out</b>, but I think I dented the car.",
        "I'm <b>freaking out</b> - I just got the job!",
        "'How's it going?' 'Oh, <b>can't complain</b> - busy but good.'",
        "Business has been steady lately, <b>can't complain</b>.",
        "'How was the trip?' 'Honestly, <b>can't complain</b> - the weather was perfect.'",
        "The boss is <b>in a good mood</b> today, so now's the time to ask.",
        "I woke up <b>in a good mood</b> for no particular reason.",
        "She's always <b>in a good mood</b> on Fridays.",
        "He's been <b>down in the dumps</b> since the breakup.",
        "I get a little <b>down in the dumps</b> when it rains for days.",
        "She seemed <b>down in the dumps</b>, so I brought her a coffee.",
        "I was so <b>bummed out</b> when they cancelled the concert.",
        "Don't be <b>bummed</b> - there'll be other chances.",
        "He's pretty <b>bummed out</b> about not making the team.",
        "They're <b>over the moon</b> about the new baby.",
        "I was <b>over the moon</b> when I got the acceptance letter.",
        "She got the promotion and she's absolutely <b>over the moon</b>.",
        "The test came back negative - <b>what a relief</b>!",
        "You found my wallet? Oh, <b>what a relief</b>.",
        "They extended the deadline. <b>What a relief</b>, honestly.",
        "I <b>can't wait</b> for the weekend.",
        "We <b>can't wait</b> to see you guys next month!",
        "She <b>can't wait</b> to move into the new place.",
        "I'm so <b>pumped</b> for the game tonight.",
        "She's really <b>pumped</b> about starting her new job.",
        "We're all <b>pumped</b> to finally meet the team in person.",
        "I've been feeling <b>a bit off</b> all day - I might be getting sick.",
        "He seemed <b>a bit off</b> at the meeting, not his usual self.",
        "Something feels <b>a bit off</b> about this whole situation.",
        "Don't get so <b>worked up</b> over a comment on the internet.",
        "He was all <b>worked up</b> about the referee's call.",
        "I got myself <b>worked up</b> over nothing - the meeting was fine.",
        "We broke up months ago - I'm totally <b>over it</b> now.",
        "Honestly, I'm so <b>over it</b>. I don't care what they decide anymore.",
        "She was upset yesterday, but she's <b>over it</b> today.",
        "I have <b>mixed feelings</b> about moving - excited but also nervous.",
        "She's got <b>mixed feelings</b> about her ex reaching out.",
        "Honestly, I have <b>mixed feelings</b> about how the show ended.",
        "I'm <b>not a fan</b> of horror movies, honestly.",
        "She's <b>not a fan</b> of the new office layout.",
        "<b>Not a fan</b> of cilantro, it tastes like soap to me.",
        "Pizza for dinner? <b>I'm all for it</b>.",
        "If it means less work for me, <b>I'm all for it</b>.",
        "You wanna leave early? Honestly, <b>I'm all for it</b>.",
        "<b>I couldn't agree more</b>, that place is way too expensive.",
        "You said it. <b>I couldn't agree more</b>.",
        "<b>I couldn't agree more</b> with what she just said.",
        "<b>That's a good point</b>, I hadn't considered the cost.",
        "Huh, <b>good point</b>. Maybe we should wait.",
        "<b>That's a good point</b>, but I still think we should try.",
        "Oh, <b>that makes sense</b>, no wonder he was upset.",
        "<b>Makes sense</b>. Let's do it that way then.",
        "Yeah, when you put it like that, <b>it makes sense</b>.",
        "<b>I see your point</b>, but I still think it's too risky.",
        "Okay, <b>I see your point</b>, maybe I was being unfair.",
        "<b>I see your point</b> about the timing.",
        "<b>I hear you</b>, this week has been exhausting.",
        "Yeah, <b>I hear you</b>, traffic was insane today too.",
        "<b>I hear you</b>, but there's not much we can do about it.",
        "I'd never pay that much for a coffee, but <b>to each their own</b>.",
        "He loves pineapple on pizza. <b>To each their own</b>, I guess.",
        "You don't like the beach? <b>To each their own</b>.",
        "Calling it 'the best restaurant in town'? <b>That's a stretch</b>.",
        "<b>That's a bit of a stretch</b>, she barely helped at all.",
        "Saying he's a genius is <b>a stretch</b>, if you ask me.",
        "The ending of that show <b>blew my mind</b>.",
        "<b>It blew my mind</b> how cheap everything was there.",
        "That documentary totally <b>blew my mind</b>.",
        "<b>I'm torn</b>, both apartments are great.",
        "Honestly, <b>I'm torn</b> on whether to take the job.",
        "<b>I'm torn</b> between the pasta and the burger.",
        "We lost the deal, but <b>it is what it is</b>.",
        "I wish it were different, but <b>it is what it is</b>.",
        "<b>It is what it is</b>, no point stressing about it now.",
        "You forgot? <b>No big deal</b>, we can reschedule.",
        "It's <b>no big deal</b>, I was happy to help.",
        "Relax, missing one class is <b>no big deal</b>."
      ]
    },
    {
      id: "gym-fitness",
      name: "Gym & Fitness",
      lines: [
        "I'm gonna <b>hit the gym</b> after work \u2014 you in?",
        "I try to <b>hit the gym</b> at least four times a week.",
        "We <b>hit the gym</b> hard last night, so I'm pretty wrecked today.",
        "Do you <b>work out</b>? You look like you're in great shape.",
        "I <b>work out</b> first thing in the morning before the gym gets busy.",
        "I've been <b>working out</b> a lot lately and honestly I feel amazing.",
        "Always <b>warm up</b> before you start lifting heavy.",
        "I <b>warm up</b> with five minutes on the treadmill and some stretches.",
        "We didn't <b>warm up</b> properly and I ended up tweaking my shoulder.",
        "I really need to <b>get in shape</b> before the wedding.",
        "He started running to <b>get in shape</b> after the holidays.",
        "It's gonna take a couple months to <b>get in shape</b> again.",
        "Hey man, can you <b>spot me</b> on this set?",
        "<b>Spot me</b> on the last couple reps, yeah?",
        "I never go heavy on bench unless someone can <b>spot me</b>.",
        "I want a workout that actually makes me <b>break a sweat</b>.",
        "That was so light I didn't even <b>break a sweat</b>.",
        "Ten minutes on the rower and you'll definitely <b>break a sweat</b>.",
        "I can barely walk today \u2014 yesterday was <b>leg day</b>.",
        "Ugh, it's <b>leg day</b>. Pray for me.",
        "Never skip <b>leg day</b>, seriously.",
        "If you wanna build strength, you've gotta <b>lift heavy</b>.",
        "I don't <b>lift heavy</b> anymore \u2014 my knees can't handle it.",
        "He <b>lifts heavy</b> four days a week and it shows.",
        "I keep track of my <b>reps and sets</b> so I know I'm actually progressing.",
        "Don't just wing it \u2014 plan out your <b>reps and sets</b> ahead of time.",
        "What kind of <b>reps and sets</b> are you doing to build size?",
        "I just <b>hit a PR</b> on deadlift \u2014 finally pulled 405!",
        "She <b>hit a PR</b> in her 5K this past weekend.",
        "Trained hard all month and I finally <b>hit a PR</b> today.",
        "My legs are <b>so sore</b> from squats yesterday.",
        "I'm gonna be <b>so sore</b> tomorrow, I can already tell.",
        "I've been <b>so sore</b> all week from that new program.",
        "I run a few times a week just to <b>stay in shape</b>.",
        "At my age you have to work a lot harder to <b>stay in shape</b>.",
        "She plays soccer on weekends mostly to <b>stay in shape</b>.",
        "The last two reps are always brutal, but you just gotta <b>push through</b>.",
        "I was completely gassed, but I <b>pushed through</b> and finished the run.",
        "When your legs start burning, that's exactly when you <b>push through</b>.",
        "I've been stuck at the same weight for a month\u2014I think I <b>hit a plateau</b>.",
        "I <b>hit a plateau</b> on my bench, so I switched up my whole program.",
        "It's totally normal to <b>hit a plateau</b> after a few months of steady progress.",
        "I'm trying to <b>lose weight</b> before summer.",
        "Cardio alone won't help you <b>lose weight</b> if your diet's a mess.",
        "She managed to <b>lose weight</b> just by cutting out soda.",
        "He's trying to <b>bulk up</b> for football season.",
        "I'm gonna <b>bulk up</b> over the winter and then cut in the spring.",
        "You won't <b>bulk up</b> just doing pushups\u2014you've gotta lift heavy and eat big.",
        "Sunday's my <b>cheat day</b>, so I'm getting pizza and ice cream.",
        "I stay strict all week and save everything for one <b>cheat day</b>.",
        "Relax, one <b>cheat day</b> isn't gonna ruin your progress.",
        "I can't, I'm <b>on a diet</b>\u2014no beer this month.",
        "She's been <b>on a diet</b> for six weeks and it's really paying off.",
        "Every time I go <b>on a diet</b>, I cave by day three.",
        "I just hit a new <b>personal best</b> on deadlift\u2014315 pounds!",
        "That run was a <b>personal best</b>, I've never gone that fast.",
        "He beat his <b>personal best</b> by almost ten seconds."
      ]
    },
    {
      id: "travel",
      name: "Travel",
      lines: [
        "Let's get there early so we have time to <b>check in</b> and drop off our bags.",
        "You can <b>check in</b> online 24 hours before the flight and just show up with your boarding pass.",
        "Did you already <b>check in</b>, or do we need to find a kiosk?",
        "I only travel with a <b>carry-on</b> so I never have to wait at baggage claim.",
        "Is this small enough to count as a <b>carry-on</b>, or will they make me check it?",
        "Keep your liquids under three ounces if they're in your <b>carry-on</b>.",
        "It's a short trip, so I'm not going to <b>check a bag</b> this time.",
        "If you <b>check a bag</b>, it's an extra sixty bucks each way now.",
        "We had to <b>check our bags</b> because the overhead bins were already full.",
        "We've got a three-hour <b>layover</b> in Chicago, so let's grab lunch there.",
        "I booked the cheaper ticket, but it has a long <b>layover</b> in Dallas.",
        "It's a direct flight, no <b>layover</b>, thank god.",
        "I can't stay long, I've got to <b>catch a flight</b> at six.",
        "We barely made it through security in time to <b>catch our flight</b>.",
        "She left the meeting early to <b>catch a flight</b> back to Toronto.",
        "If we land late, there's no way I'll <b>make my connection</b>.",
        "We had twenty minutes to <b>make our connection</b> and had to sprint across the terminal.",
        "The delay was short enough that everyone still <b>made their connection</b>.",
        "They just called our group, so let's <b>board the plane</b>.",
        "We started <b>boarding the plane</b> almost an hour late.",
        "You get to <b>board the plane</b> early if you're traveling with little kids.",
        "I took the <b>red-eye</b> so I could be in the office by nine.",
        "<b>Red-eyes</b> are brutal, I can never sleep on the plane.",
        "It was way cheaper to fly the <b>red-eye</b> back from Vegas.",
        "Give yourself extra time, the line to <b>go through security</b> is huge today.",
        "Once you <b>go through security</b>, there are a bunch of places to eat.",
        "I always <b>get through security</b> faster with PreCheck.",
        "I'm so <b>jet-lagged</b> I woke up at 4 a.m. absolutely starving.",
        "Give me a day, I'm still pretty <b>jet-lagged</b> from the flight.",
        "The kids were fine, but I was <b>jet-lagged</b> for a week.",
        "Bad news, our <b>flight's delayed</b> by two hours.",
        "Half the <b>flights are delayed</b> because of the storm in Denver.",
        "My <b>flight got delayed</b>, so I'm going to miss the connection.",
        "Meet me down at <b>baggage claim</b>, carousel 5.",
        "We stood at <b>baggage claim</b> for forty minutes and my suitcase never showed up.",
        "If you've only got a carry-on, you can skip <b>baggage claim</b> entirely.",
        "Text me when you land and I'll come <b>pick you up</b>.",
        "Can someone <b>pick me up</b> at arrivals, or should I just grab an Uber?",
        "I'll <b>pick you up</b> out front, just look for the blue Honda.",
        "What time do we have to <b>check out</b> tomorrow?",
        "We <b>checked out</b> early to catch the first train.",
        "Can I leave my bags here after I <b>check out</b>?",
        "The subway makes it really easy to <b>get around</b> the city.",
        "What's the best way to <b>get around</b> without renting a car?",
        "Once you figure out the buses, it's cheap to <b>get around</b>.",
        "It's pouring out \u2014 let's just <b>grab a cab</b> back to the hotel.",
        "We were running late, so we <b>grabbed a cab</b> to the airport.",
        "You can <b>grab a cab</b> right outside the terminal.",
        "Skip that restaurant by the square \u2014 it's a total <b>tourist trap</b>.",
        "The old town is nice, but the main strip is kind of a <b>tourist trap</b>.",
        "I heard it's a <b>tourist trap</b>, so let's find somewhere the locals actually go.",
        "We wanted somewhere <b>off the beaten path</b>, away from all the crowds.",
        "This little town is really <b>off the beaten path</b> \u2014 barely any tourists.",
        "If you go a bit <b>off the beaten path</b>, the prices drop a lot.",
        "That caf\u00e9 was a real <b>hidden gem</b> \u2014 no tourists, amazing coffee.",
        "Ask a local; they always know the <b>hidden gems</b>.",
        "The beach on the north side is a <b>hidden gem</b> \u2014 hardly anyone goes there.",
        "We've got two days to <b>see the sights</b> before we fly home.",
        "Do you want to <b>see the sights</b> or just relax by the pool?",
        "We spent the morning <b>seeing the sights</b> downtown.",
        "We're taking a <b>day trip</b> to the coast on Saturday.",
        "It's an easy <b>day trip</b> from the city \u2014 about an hour each way.",
        "Instead of staying over, we just did a <b>day trip</b>.",
        "Give me ten minutes to <b>settle in</b> and then we can head out.",
        "Once we <b>settled in</b>, the place actually started to feel like home.",
        "We barely had time to <b>settle in</b> before dinner.",
        "The hotel's great \u2014 everything's <b>within walking distance</b>.",
        "Are the restaurants <b>within walking distance</b>, or do we need a cab?",
        "We picked this place because the beach is <b>within walking distance</b>.",
        "If you're in town, the market is an absolute <b>must-see</b>.",
        "Everyone says the old cathedral is a <b>must-see</b>.",
        "Honestly, that viewpoint is a <b>must-see</b> at sunset."
      ]
    },
    {
      id: "restaurants",
      name: "Restaurants",
      lines: [
        "<b>Can I get</b> the cheeseburger with fries, please?",
        "Hi, <b>can I get</b> a large iced coffee and a blueberry muffin?",
        "<b>Can I get</b> another round over here whenever you get a sec?",
        "<b>I'll have</b> the grilled salmon, and can I swap the rice for veggies?",
        "<b>I'll have</b> a glass of the house red, thanks.",
        "I think <b>I'll have</b> the special tonight.",
        "First time here - <b>what do you recommend?</b>",
        "I can't decide between these two. <b>What do you recommend?</b>",
        "<b>What do you recommend</b> if I'm really hungry?",
        "That was great. <b>Can we get the check</b> whenever you're ready?",
        "We're kind of in a hurry - <b>can we get the check</b>, please?",
        "<b>Can we get the check?</b> And we'll split it two ways.",
        "Oh, I'm <b>still working on it</b>, thanks.",
        "Can you leave that? She's <b>still working on it</b>.",
        "No, no, I'm <b>still working on it</b> - just taking my time.",
        "That sounds good - <b>I'll have the same</b>.",
        "<b>I'll have the same</b>, but no onions, please.",
        "Two of those? Yeah, <b>I'll have the same</b>.",
        "Can I get the dressing <b>on the side</b>?",
        "I'll take the burger, but put the sauce <b>on the side</b>, please.",
        "Fries with a little ranch <b>on the side</b> would be great.",
        "Can I get a large fries <b>to go</b>?",
        "Actually, could you make that <b>to go</b>? We've gotta run.",
        "Can we get the rest of this boxed up <b>to go</b>?",
        "<b>For starters</b>, we'll do the calamari and the bruschetta.",
        "<b>For starters</b>, can we get an order of wings for the table?",
        "Let's get something <b>for starters</b> - maybe the soup?",
        "Should I <b>make a reservation</b>, or do you think we can just walk in?",
        "I <b>made a reservation</b> for four at seven under the name Silva.",
        "This place gets packed on weekends, so we'd better <b>make a reservation</b>.",
        "Man, that cold beer really <b>hit the spot</b> after work.",
        "I was starving \u2014 that burger totally <b>hit the spot</b>.",
        "Nothing <b>hits the spot</b> like pizza on a Friday night.",
        "No dessert for me, thanks \u2014 <b>I'm stuffed</b>.",
        "That was amazing, but <b>I'm stuffed</b>. I can't eat another bite.",
        "We ordered way too much. <b>I'm so stuffed</b>.",
        "After that Thanksgiving dinner I went straight into a <b>food coma</b>.",
        "I can't move \u2014 total <b>food coma</b> right now.",
        "Careful, that much pasta will put you in a <b>food coma</b>.",
        "Should we just <b>split the check</b> four ways?",
        "Do you guys want separate bills, or should we <b>split the check</b>?",
        "Let's <b>split the check</b> \u2014 I'll leave the tip.",
        "Put your wallet away \u2014 <b>it's on me</b> tonight.",
        "You paid last time, so tonight <b>it's on me</b>.",
        "Order whatever you want, <b>it's on me</b>.",
        "It's just <b>a hole in the wall</b>, but they make the best tacos in town.",
        "We found this little <b>hole-in-the-wall</b> ramen spot downtown.",
        "Don't let the look fool you \u2014 some of the best food is at these <b>hole-in-the-wall</b> places."
      ]
    },
    {
      id: "shopping",
      name: "Shopping",
      lines: [
        "\"Need help finding anything?\" \"No thanks, <b>just browsing</b>.\"",
        "If you're <b>just browsing</b>, no worries \u2014 I'll be right over here if you have questions.",
        "I went in <b>just browsing</b> and somehow walked out with three pairs of shoes.",
        "These jeans are <b>on sale</b> \u2014 thirty percent off this week.",
        "I always wait for stuff to go <b>on sale</b> before I buy it.",
        "Are these <b>on sale</b>, or is that just the regular price?",
        "Forty bucks for all this? That's <b>a good deal</b>.",
        "You got <b>a really good deal</b> on that TV.",
        "Shop around a little \u2014 you might find <b>a better deal</b> online.",
        "I wanted the black one, but they were <b>sold out</b>.",
        "The concert tickets <b>sold out</b> in like ten minutes.",
        "Sorry, we're <b>sold out</b> of that size right now.",
        "You can <b>try it on</b> \u2014 the fitting rooms are in the back.",
        "I never buy jeans without <b>trying them on</b> first.",
        "Do you wanna <b>try that on</b> before you decide?",
        "Let me check if we've got that <b>in stock</b>.",
        "Is the large <b>in stock</b>, or would I have to order it?",
        "They finally got the new model back <b>in stock</b>.",
        "Don't buy the first one you see \u2014 <b>shop around</b> a little.",
        "I <b>shopped around</b> and found it fifty bucks cheaper somewhere else.",
        "It really pays to <b>shop around</b> before a big purchase.",
        "Ten bucks for that jacket? That's <b>a steal</b>.",
        "At that price it's <b>an absolute steal</b>.",
        "The couch was practically <b>a steal</b> at the estate sale.",
        "Twelve dollars for a bottle of water? What a <b>rip-off</b>.",
        "That place is a total <b>rip-off</b> \u2014 everything's marked way up.",
        "I felt like I got <b>ripped off</b> on that repair.",
        "I can <b>ring you up</b> over here whenever you're ready.",
        "Is somebody <b>ringing you up</b> already?",
        "She <b>rang me up</b> and I was out the door in a minute.",
        "Just <b>put it on my card</b> \u2014 I don't have any cash on me.",
        "You can <b>put it on my card</b> and I'll pay you back later.",
        "Actually, can you <b>put it on my card</b>? The other one's maxed out.",
        "There's no line at register 3 if you want to <b>ring it up</b> over there.",
        "Can you <b>ring me up</b>? I'm kind of in a hurry.",
        "Wait, it <b>rang up</b> as $40 \u2014 I thought it was on sale for $25.",
        "Hey, <b>do you take cards</b>, or is this place cash only?",
        "<b>Do you guys take</b> Apple Pay?",
        "Quick question \u2014 <b>do you take</b> Amex?",
        "These jeans don't fit \u2014 I'm gonna <b>take them back</b> this weekend.",
        "If it doesn't work, just <b>take it back</b>; they're pretty good about returns.",
        "I <b>took it back</b>, but they'd only give me store credit.",
        "It broke after two days, so I want to <b>get my money back</b>.",
        "Can I <b>get my money back</b>, or is it exchange only?",
        "Good luck <b>getting your money back</b> without a receipt.",
        "<b>Keep the receipt</b> just in case it doesn't fit.",
        "Make sure you <b>keep the receipt</b> \u2014 you can't return anything without it.",
        "I always <b>keep my receipts</b> for the big stuff.",
        "They wouldn't refund my card, just gave me <b>store credit</b>.",
        "Without the receipt, the best they'll do is <b>store credit</b>.",
        "I've got like $30 in <b>store credit</b> I need to use up.",
        "It's pricey, but honestly it's <b>worth it</b>.",
        "Is the extended warranty even <b>worth it</b>?",
        "Don't bother \u2014 it's really not <b>worth it</b>.",
        "Go ahead and get it \u2014 twenty bucks <b>won't break the bank</b>.",
        "I wanted something nice that <b>wouldn't break the bank</b>.",
        "It's a bit of a splurge, but it's not gonna <b>break the bank</b>."
      ]
    }
  ]
};
